// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsEventsApp.Data;

#nullable disable

namespace SportsEventsApp.Data.Migrations
{
    [DbContext(typeof(SportEventsAppDbContext))]
    [Migration("20241210063700_ClearInfo")]
    partial class ClearInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fighter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The unique identifier of the fighter");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The weight class (category) of the fighter");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The nationality of the fighter");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("First name of the fighter");

                    b.Property<double>("Height")
                        .HasColumnType("float")
                        .HasComment("The height of the fighter in feet");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("URL for the fighter's image");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates wether the fighter is deleted (soft delete).");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Last name of the fighter");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nickname of the fighter");

                    b.Property<int>("Reach")
                        .HasColumnType("int")
                        .HasComment("The fighter's reach in inches");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Fighters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c415431-534f-45da-b04f-5af0130c0593"),
                            CategoryId = new Guid("4af1cb43-9d27-4f7a-8d81-e0af441ee1ec"),
                            Country = "Ireland",
                            DateOfBirth = new DateTime(1988, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Conor",
                            Height = 5.7999999999999998,
                            ImageUrl = "https://www.sherdog.com/image_crop/200/300/_images/fighter/20220325093124_Conor_McGregor_ff.JPG",
                            IsDeleted = false,
                            LastName = "McGregor",
                            NickName = "The Notorious",
                            Reach = 74
                        },
                        new
                        {
                            Id = new Guid("ee4aea7a-f7cc-4727-b233-d78685283a86"),
                            CategoryId = new Guid("4af1cb43-9d27-4f7a-8d81-e0af441ee1ec"),
                            Country = "Russia",
                            DateOfBirth = new DateTime(1988, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Khabib",
                            Height = 5.0999999999999996,
                            ImageUrl = "https://www.datocms-assets.com/99008/1696277875-untitled-design-5.png",
                            IsDeleted = false,
                            LastName = "Nurmagomedov",
                            NickName = "The Eagle",
                            Reach = 70
                        },
                        new
                        {
                            Id = new Guid("a593799f-c4b5-43f7-a19d-f2f0b4d388e2"),
                            CategoryId = new Guid("1de95a26-05ea-4b66-82f1-c0c912ac1780"),
                            Country = "Brazil",
                            DateOfBirth = new DateTime(1987, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alex",
                            Height = 6.4000000000000004,
                            ImageUrl = "https://dmxg5wxfqgb4u.cloudfront.net/styles/card_advance_small_280x356/s3/2024-10/100324-Alex-Pereira-UFC-307-Press-Conference-THUMB-GettyImages-2176549340.jpg?itok=5C_djKwj",
                            IsDeleted = false,
                            LastName = "Pereira",
                            NickName = "Poatan",
                            Reach = 79
                        },
                        new
                        {
                            Id = new Guid("ccfae67c-d409-4084-a27a-eb1042b917bf"),
                            CategoryId = new Guid("1de95a26-05ea-4b66-82f1-c0c912ac1780"),
                            Country = "Nigeria",
                            DateOfBirth = new DateTime(1989, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Israel",
                            Height = 6.4000000000000004,
                            ImageUrl = "https://glory.pinkyellow.network/assets/fighters/israel-the-last-style-bender-adesanya/thumbnail.jpg",
                            IsDeleted = false,
                            LastName = "Adesanya",
                            NickName = "The Last Stylebender",
                            Reach = 80
                        },
                        new
                        {
                            Id = new Guid("c58ca473-6b7d-457b-b221-155b1cf97a2a"),
                            CategoryId = new Guid("1de95a26-05ea-4b66-82f1-c0c912ac1780"),
                            Country = "Brazil",
                            DateOfBirth = new DateTime(1975, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anderson",
                            Height = 6.2000000000000002,
                            ImageUrl = "https://www.denverpost.com/wp-content/uploads/2016/04/20140801_084436_anderson-silva.jpg?w=640",
                            IsDeleted = false,
                            LastName = "Silva",
                            NickName = "The Spider",
                            Reach = 77
                        },
                        new
                        {
                            Id = new Guid("ec004262-6905-4b60-b996-80bf229c8b0d"),
                            CategoryId = new Guid("1de95a26-05ea-4b66-82f1-c0c912ac1780"),
                            Country = "U.S.",
                            DateOfBirth = new DateTime(1977, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Chael",
                            Height = 6.0999999999999996,
                            ImageUrl = "https://www.sherdog.com/image_crop/200/300/_images/fighter/20131219125416_chael_sonnen.JPG",
                            IsDeleted = false,
                            LastName = "Sonnen",
                            NickName = "The American Gangster",
                            Reach = 73
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "40897789-0c7c-4c6e-ba51-9bef53f3857a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f2d08bdf-5a0a-481a-9f78-f61c7de1603b",
                            Email = "admin@mma.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MMA.COM",
                            NormalizedUserName = "ADMIN@MMA.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEnCM+EI5/ZnasFKomCRurtWKToMb+OaRg30CaNp7q/8VknQRa3p7J/QBJTPf6otrg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7c1a6dee-e7ea-4be9-98ff-a3a434aba917",
                            TwoFactorEnabled = false,
                            UserName = "admin@mma.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SportsEventsApp.Data.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The id of the category");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("float")
                        .HasComment("The minimum required weight needed to clasify as this weight, in pounds.");

                    b.Property<double>("MinWeight")
                        .HasColumnType("float")
                        .HasComment("The minimum required weight needed to clasify as this weight, in pounds.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The name of the category, exemple: LightWeight, MiddleWeight....");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39cd5933-0c36-4049-9122-d40c88524b23"),
                            MaxWeight = 115.0,
                            MinWeight = 106.0,
                            Name = "Strawweight"
                        },
                        new
                        {
                            Id = new Guid("282b2512-55ad-46ff-b251-464ebbd8bf79"),
                            MaxWeight = 125.0,
                            MinWeight = 115.0,
                            Name = "Flyweight"
                        },
                        new
                        {
                            Id = new Guid("7bfdc7d9-8eab-43e1-b162-726127c9f755"),
                            MaxWeight = 135.0,
                            MinWeight = 125.0,
                            Name = "Bantamweight"
                        },
                        new
                        {
                            Id = new Guid("1f80fdd2-e931-4e70-8432-8f25cb3569c1"),
                            MaxWeight = 145.0,
                            MinWeight = 135.0,
                            Name = "Featherweight"
                        },
                        new
                        {
                            Id = new Guid("4af1cb43-9d27-4f7a-8d81-e0af441ee1ec"),
                            MaxWeight = 155.0,
                            MinWeight = 145.0,
                            Name = "Lightweight"
                        },
                        new
                        {
                            Id = new Guid("1d8e06f1-8a66-42a5-9ed1-c22068a602f1"),
                            MaxWeight = 170.0,
                            MinWeight = 155.0,
                            Name = "Welterweight"
                        },
                        new
                        {
                            Id = new Guid("1de95a26-05ea-4b66-82f1-c0c912ac1780"),
                            MaxWeight = 185.0,
                            MinWeight = 170.0,
                            Name = "Middleweight"
                        },
                        new
                        {
                            Id = new Guid("bce83443-00cf-4522-84f7-0ab4062141cf"),
                            MaxWeight = 205.0,
                            MinWeight = 185.0,
                            Name = "Light Heavyweight"
                        },
                        new
                        {
                            Id = new Guid("fb4c64cd-67f0-45b7-acf3-759ed5f3307f"),
                            MaxWeight = 265.0,
                            MinWeight = 205.0,
                            Name = "Heavyweight"
                        });
                });

            modelBuilder.Entity("SportsEventsApp.Data.Fight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Unique identifier of the fight");

                    b.Property<DateTime>("DateOfTheFight")
                        .HasColumnType("datetime2")
                        .HasComment("The date of the fight, not the date of its adding");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("A brief decription of the fight details, also has a minimum and maximum characher limit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("url of the image");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("this is a bool that keeps track of the status of the fight- deleted or not (soft delete)");

                    b.Property<string>("PublisherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("The id of the admin that added the fight, note that users and guests cannot add or delete fights");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("The name of the title, has a minimum and maximum characher limit");

                    b.Property<string>("YouTubeUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The link to the youtube video of the fight");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Fights");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ab04830-9655-4064-a4a9-907a4454185b"),
                            DateOfTheFight = new DateTime(2018, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A legendary UFC fight between two icons of the sport.",
                            ImageUrl = "https://i.ytimg.com/vi/JuBBIJ7adjM/hq720.jpg",
                            IsDeleted = false,
                            PublisherId = "40897789-0c7c-4c6e-ba51-9bef53f3857a",
                            Title = "Conor McGregor vs Khabib Nurmagomedov",
                            YouTubeUrl = "https://www.youtube.com/watch?v=JuBBIJ7adjM"
                        },
                        new
                        {
                            Id = new Guid("3c367b70-fb1e-48cc-a40e-847e07a3a8d3"),
                            DateOfTheFight = new DateTime(2023, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A thrilling bout between two fierce rivals.",
                            ImageUrl = "https://www.bet-experts.com/wp-content/uploads/2023/04/ufc-287-bet-experts.jpg",
                            IsDeleted = false,
                            PublisherId = "40897789-0c7c-4c6e-ba51-9bef53f3857a",
                            Title = "Israel Adesanya vs Alex Pereira",
                            YouTubeUrl = "https://www.youtube.com/watch?v=yKdi_7cscd0"
                        },
                        new
                        {
                            Id = new Guid("a19b3d06-a213-4ac3-837c-f5ae4f87c133"),
                            DateOfTheFight = new DateTime(2012, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A classic middleweight bout filled with drama.",
                            ImageUrl = "https://i.ytimg.com/vi/ugQCRH9f5QU/maxresdefault.jpg",
                            IsDeleted = false,
                            PublisherId = "40897789-0c7c-4c6e-ba51-9bef53f3857a",
                            Title = "Anderson Silva vs Chael Sonnen",
                            YouTubeUrl = "https://www.youtube.com/watch?v=DpLaqnwFQEY"
                        });
                });

            modelBuilder.Entity("SportsEventsApp.Data.FighterFight", b =>
                {
                    b.Property<Guid>("FighterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FightId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FighterId", "FightId");

                    b.HasIndex("FightId");

                    b.ToTable("FightersFights");

                    b.HasData(
                        new
                        {
                            FighterId = new Guid("4c415431-534f-45da-b04f-5af0130c0593"),
                            FightId = new Guid("1ab04830-9655-4064-a4a9-907a4454185b")
                        },
                        new
                        {
                            FighterId = new Guid("ee4aea7a-f7cc-4727-b233-d78685283a86"),
                            FightId = new Guid("1ab04830-9655-4064-a4a9-907a4454185b")
                        },
                        new
                        {
                            FighterId = new Guid("ccfae67c-d409-4084-a27a-eb1042b917bf"),
                            FightId = new Guid("3c367b70-fb1e-48cc-a40e-847e07a3a8d3")
                        },
                        new
                        {
                            FighterId = new Guid("a593799f-c4b5-43f7-a19d-f2f0b4d388e2"),
                            FightId = new Guid("3c367b70-fb1e-48cc-a40e-847e07a3a8d3")
                        },
                        new
                        {
                            FighterId = new Guid("ec004262-6905-4b60-b996-80bf229c8b0d"),
                            FightId = new Guid("a19b3d06-a213-4ac3-837c-f5ae4f87c133")
                        },
                        new
                        {
                            FighterId = new Guid("c58ca473-6b7d-457b-b221-155b1cf97a2a"),
                            FightId = new Guid("a19b3d06-a213-4ac3-837c-f5ae4f87c133")
                        });
                });

            modelBuilder.Entity("SportsEventsApp.Data.UserFight", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("FightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ListType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Indicates whether the fight is in the user's Watchlist or Favorites");

                    b.HasKey("UserId", "FightId", "ListType");

                    b.HasIndex("FightId");

                    b.ToTable("UsersFights");
                });

            modelBuilder.Entity("Fighter", b =>
                {
                    b.HasOne("SportsEventsApp.Data.Category", "Category")
                        .WithMany("Fighters")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportsEventsApp.Data.Fight", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("SportsEventsApp.Data.FighterFight", b =>
                {
                    b.HasOne("SportsEventsApp.Data.Fight", "Fight")
                        .WithMany("FighterFights")
                        .HasForeignKey("FightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fighter", "Fighter")
                        .WithMany("FighterFights")
                        .HasForeignKey("FighterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Fight");

                    b.Navigation("Fighter");
                });

            modelBuilder.Entity("SportsEventsApp.Data.UserFight", b =>
                {
                    b.HasOne("SportsEventsApp.Data.Fight", "Fight")
                        .WithMany("UsersFights")
                        .HasForeignKey("FightId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Fight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fighter", b =>
                {
                    b.Navigation("FighterFights");
                });

            modelBuilder.Entity("SportsEventsApp.Data.Category", b =>
                {
                    b.Navigation("Fighters");
                });

            modelBuilder.Entity("SportsEventsApp.Data.Fight", b =>
                {
                    b.Navigation("FighterFights");

                    b.Navigation("UsersFights");
                });
#pragma warning restore 612, 618
        }
    }
}
